repos:
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1  # Use the latest stable version for flake8
    hooks:
      - id: flake8
  - repo: https://github.com/hhatto/autopep8
    rev: 'v2.3.1'
    hooks:
      - id: autopep8