[tool.poetry]
name = "blog app with drf"
version = "0.1.0"
description = ""
authors = ["seela-2001 <sohilamustafa68@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.1.4"


[tool.poetry.group.dev.dependencies]
autopep8 = "^2.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
