# Generated by Django 5.1.4 on 2024-12-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_newuser_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="newuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
